services:
  mongodb:
    image: mongo:7
    container_name: im-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: MyNew@2025Safe
      MONGO_INITDB_DATABASE: safechat
    volumes:
      - mongodb_data:/data/db
    networks:
      - im-network
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: im-backend
    restart: always
    ports:
      - "3000:3001"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: "mongodb://admin:MyNew%402025Safe@mongodb:27017/safechat?authSource=admin"
      JWT_SECRET: "super_secret_safechat_key_2025"
      PORT: "3001"
      ALLOWED_ORIGINS: "*"
    networks:
      - im-network

  frontend:
    image: nginx:alpine
    container_name: im-frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend/modern:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - im-network

volumes:
  mongodb_data:

networks:
  im-network:
    driver: bridge
