name: Docker Compose Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-docker-compose:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Test docker-compose configuration
      run: docker compose config
    
    - name: Build and start services
      run: docker compose up -d --build
    
    - name: Wait for services to be ready
      run: sleep 60

    - name: Check services are running
      run: docker compose ps

    - name: Show mongodb logs
      if: always()
      run: docker compose logs mongodb --tail 200

    - name: Test backend health endpoint
      run: |
        for i in {1..24}; do
          if curl -f http://localhost:3000/health; then
            echo "Backend is healthy"
            exit 0
          fi
          echo "Waiting for backend... attempt $i"
          sleep 5
        done
        echo "Backend health check failed - printing debug logs"
        echo "=== docker compose ps ==="
        docker compose ps
        echo "=== backend recent logs ==="
        docker compose logs backend --tail 500
        echo "=== mongodb recent logs ==="
        docker compose logs mongodb --tail 200
        exit 1
    
    - name: Test frontend accessibility
      run: |
        curl -f http://localhost/ || (docker compose logs frontend && exit 1)
    
    - name: Cleanup
      if: always()
      run: docker compose down -v
