    [![.github/workflows/docker-compose.yml](https://github.com/Gymmmm/im-safechat/actions/workflows/docker-compose.yml/badge.svg)](https://github.com/Gymmmm/im-safe		chat/actions/workflows/docker-compose.yml)
