name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Backend Docker image
      run: docker build -t safechat-backend:latest -f ./backend/Dockerfile ./backend
    
    - name: Start MongoDB for testing
      run: |
        docker run -d --name test-mongodb \
          -e MONGO_INITDB_ROOT_USERNAME=admin \
          -e MONGO_INITDB_ROOT_PASSWORD=testpass \
          -p 27017:27017 \
          mongo:7
        sleep 10
    
    - name: Test backend image
      run: |
        docker run -d --name test-backend \
          --network host \
          -e MONGODB_URI=mongodb://admin:testpass@localhost:27017/safechat?authSource=admin \
          -e JWT_SECRET=test_secret \
          -e PORT=3001 \
          safechat-backend:latest
        sleep 10
        echo "=== Backend logs ==="
        docker logs test-backend
        echo "=== Testing health endpoint ==="
        curl -f http://localhost:3001/health || (docker logs test-backend && exit 1)
        docker stop test-backend test-mongodb
        docker rm test-backend test-mongodb

  test-docker-compose:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Test docker-compose configuration
      run: docker compose config
    
    - name: Build and start services
      run: docker compose up -d --build
    
    - name: Wait for services to be ready
      run: sleep 30
    
    - name: Check services status
      run: docker compose ps
    
    - name: Check backend health
      run: |
        docker compose logs backend
        curl -f http://localhost:3000/health || echo "Health check endpoint may not exist"
    
    - name: Stop services
      run: docker compose down -v
